language: go
go:
    - 1.9.x
    - tip
matrix:
    fast_finish: true
    allow_failures:
        - go: tip
before_install:
    - go get github.com/mattn/goveralls
script:
    - $GOPATH/bin/goveralls -service=travis-ci -v
